name: Terraform Security Scan (tfsec)

# Controls when the workflow will run
on:
  push:
    branches: [ "*" ]
    paths-ignore:
      - '**/README.md'
      - 'Documentation/**'
      - 'Verification/**'
    # paths:
    # - terraform/**
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - 'Documentation/**'
      - 'Verification/**'
    #schedule:
    # Run a full scan every day at midnight UTC
    #- cron: "0 0 * * *"
  workflow_dispatch: # Allow manual trigger

permissions:
  id-token: write         # Required for requesting the OIDC JWT
  contents: read          # Required for actions/checkout
  security-events: write  # for github/codeql-action/upload-sarif to upload SARIF results
  actions: read           # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
  pull-requests: write    # Required for plan comments
  issues: write

env:
  # Force all JavaScript actions to run on Node.js 24 to silence Node 20 deprecation warnings
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  # verbosity setting for Terraform logs
  TF_LOG: INFO
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  TF_BACKEND_S3_BUCKET: ${{ vars.TF_BACKEND_S3_BUCKET }}
  TF_VERSION: ${{ vars.TF_VERSION }}
  # WORKING_DIR: './terraform'

jobs:
  tfsec:
    name: tfsec Security Scan
    runs-on: ubuntu-latest
    environment: dev

    steps:
        # ── Checkout source ───────────────────────────────────────────────
      - name: Checkout Repository
        uses: actions/checkout@v4

        # ── Configure AWS credentials (OIDC) ───────────────────────────────────────────────
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_ARN }}

        # ── Install tfsec ───────────────────────────────────────────────
      - name: Install tfsec
        run: |
          TFSEC_VERSION="v1.28.11"
          curl -sL "https://github.com/aquasecurity/tfsec/releases/download/${TFSEC_VERSION}/tfsec-linux-amd64" \
            -o /usr/local/bin/tfsec
          chmod +x /usr/local/bin/tfsec
          tfsec --version

        # ── Checkout source ───────────────────────────────────────────────
      - name: Run tfsec
        run: |
          tfsec . \
            --format sarif \
            --out tfsec-results.sarif \
            --soft-fail
        # Change '.' to './terraform' if your Terraform code is in a subdirectory

      - name: Upload SARIF to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: tfsec-results.sarif
          category: tfsec

      - name: Archive SARIF report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tfsec-sarif-report
          path: tfsec-results.sarif
          retention-days: 7
